replicaCount: 1

image:
  repository: awwalmustapha/livekit-agent
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: 2000m
    memory: 4000Mi
  limits:
    cpu: 4000m
    memory: 6000Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # scale up at 0.5 CPU utilization

env:
  livekitUrl: "wss://livekit.awwalmustapha.online/"
  livekitApiKey: ""
  livekitApiSecret: ""
  openaiApiKey: ""
  deepgramApiKey: ""
  cartesiaApiKey: ""
