replicaCount: 1

image:
  repository: your-docker-repo/livekit-starter-agent
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # scale up at 0.5 CPU utilization

env:
  livekitUrl: ""
  livekitApiKey: ""
  livekitApiSecret: ""
  openaiApiKey: ""
  deepgramApiKey: ""
  cartesiaApiKey: ""
