# Suggested value for gracefully terminate the pod: 1 hour
terminationGracePeriodSeconds: 3600

egress:
  api_key: "sandbox-key"
  api_secret: "Yw3E1V0eFMv4Tm5ShxP1WgIYfXOt1Lzrz7EsNgP+ev4="
  ws_url: "ws://livekit-server"
  log_level: info
  health_port: 8080
  prometheus_port: 9090
  enable_chrome_sandbox: true
  redis:
    address: master.livekit-sandbox.xgc4fk.use1.cache.amazonaws.com:6379
    tls:
      enabled: true


# autoscaling requires resources to be defined
autoscaling:
  # set to true to enable autoscaling. when set, ignores replicaCount
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
#  targetMemoryUtilizationPercentage: 60
  # for use with prometheus adapter - the egress service outputs a prometheus metric called livekit_egress_available
  # this can be used to ensure a certain number or percentage of instances are available
#  custom:
#    metricName: my_metric_name
#    targetAverageValue: 70

# if egress should run only on specific nodes
# this can be used to isolate designated nodes
nodeSelector: {}
# node.kubernetes.io/instance-type: c5.2xlarge

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    cpu: 8000m
    memory: 2048Mi

serviceAccount:
  create: true
  annotations: {} ## to added from github secrets
  name: livekit-egress
podAnnotations:
  linkerd.io/inject: disabled


