# Use existing ServiceAccount
serviceAccount:
  create: true
  # name: ${service_account_name}
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::025346772603:role/loki-irsa-role
  name: loki


# Loki configuration
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: us-east-1
      bucketnames: loki-logs-bucket-sandbox
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  querier:
    max_concurrent: 4
  storage:
    type: s3
    bucketnames: 
      chunks: loki-logs-bucket-sandbox
      ruler: loki-logs-bucket-sandbox
      admin: loki-logs-bucket-sandbox
    s3:
      s3: s3://loki-logs-bucket-sandbox
      region: us-east-1
      s3ForcePathStyle: false

# Enable monitoring
serviceMonitor:
  enabled: true

deploymentMode: SimpleScalable

# Disable test pod
test:
  enabled: false

write:
  persistence:
    storageClass: ebs-sc
    size: 5Gi

read:
  persistence:
    storageClass: ebs-sc
    size: 5Gi