replicaCount: 1

image:
  repository: livekit/sip
  tag: "latest"
  pullPolicy: IfNotPresent

hostNetwork: true

serviceAccount:
  create: true
  name: ""

resources:
  limits:
    cpu: "2000m"
    memory: "2Gi"
  requests:
    cpu: "2000m"
    memory: "2Gi"

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: NodePort
  sipPort: 5060
  healthPort: 8080
  prometheusPort: 9090

sip:
  api_key: sandbox-key
  api_secret: "Yw3E1V0eFMv4Tm5ShxP1WgIYfXOt1Lzrz7EsNgP+ev4="
  ws_url: "wss://livekit.awwalmustapha.online"
  redis:
    address: db.default.svc.cluster.local:6379
  use_external_ip: true
  health_port: 8080
  prometheus_port: 9090
  log_level: debug
  sip_port: 5060
  rtp_port: 10000-20000

probes:
  enabled: true
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
  readiness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10

extraEnv: {}
extraVolumes: []
extraVolumeMounts: []
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: sip.awwalmustapha.online
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sip.awwalmustapha.online
      secretName: sip-tls

existingSecret: ""
securityContext: {}
podSecurityContext: {}
terminationGracePeriodSeconds: 300

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpu:
    enabled: true
    targetAverageUtilization: 80
  memory:
    enabled: true
    targetAverageUtilization: 80
  custom:
    enabled: false
    metricName: sip_active_sessions
    targetAverageValue: "10"   # average sessions per pod

serviceMonitor:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  interval: 30s

