loki:
  auth_enabled: false
  storage:
    type: s3
    s3:
      bucketnames: "${bucket_name}"
      region: "${region}"
      endpoint: s3.amazonaws.com
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h
