name: Test AWS OIDC Connection

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    paths:
      - 'terraform/global/iam/**'

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout repository

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    environment: sandbox  # Specify the environment if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Test AWS access
        run: |
          aws sts get-caller-identity
          echo "Successfully authenticated with AWS using OIDC!"
